// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjqeC5XR9GK0IG1AX1AOF--fPCsX1DxqI',
    appId: '1:841287433054:android:b09ad04cd572403fa3adcf',
    messagingSenderId: '841287433054',
    projectId: 'swaraashi-netralaya',
    storageBucket: 'swaraashi-netralaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX_Jtzf0KOMvTk8dKZ-4JNDzYihZdtbhk',
    appId: '1:841287433054:ios:b895cecdda07dc45a3adcf',
    messagingSenderId: '841287433054',
    projectId: 'swaraashi-netralaya',
    storageBucket: 'swaraashi-netralaya.appspot.com',
    androidClientId: '841287433054-9i95rstjg06kueaf4tn12te6pk01vo0g.apps.googleusercontent.com',
    iosClientId: '841287433054-4pmlp8r32hfqojdsej7quad7r1oj1po4.apps.googleusercontent.com',
    iosBundleId: 'com.swaraashi.swaraashinetralaya',
  );
}
